table _Measures
	lineageTag: 1b6cdce7-2f02-4b83-a66a-bce495853d0c

	measure 'Data Refresh' =
			VAR Date_Refresh =
			    SUMMARIZE ( 'Data Refresh', 'Data Refresh'[Date Time] )
			RETURN
			    FORMAT(Date_Refresh, "dd-mmm-yyyy hh:mm:ss AM/PM")
		isHidden
		lineageTag: 7a74251d-518b-4d6c-9ca3-d14b3c5fe9cb

		changedProperty = IsHidden

	measure 'Gradient Axpo' =
			"<!DOCTYPE html>
			<html>
			<head>
			    <meta charset='UTF-8'>
			    <style>
			        body {
			            margin: 0;
			            background: linear-gradient(to right, #ee5b6f, #d7597a, #b25491, #8b4da6, #764cb5);
			            min-height: 100vh;
			        }
			    </style>
			</head>
			<body>
			</body>
			</html>"
		isHidden
		lineageTag: 570cdd5f-b1a5-4522-999f-05948b6e204e

		changedProperty = IsHidden

	measure 'Total revenue €' = SUM(Fact_Sales[Revenue_EUR])
		formatString: 0
		lineageTag: e97a5454-962f-4079-ab91-be04bdd123d8

	measure 'Total Cost €' = SUM(Fact_Sales[Cost_EUR])
		formatString: 0
		lineageTag: 1af09593-049a-4051-ac8d-ee5226ff8100

	measure 'Gross Margin €' = sum(Fact_Sales[GrossMargin_EUR])
		formatString: 0
		lineageTag: 6b8f9bd9-4442-412e-9ed5-99723b414cec

	measure 'Total Volume (MWh)' = SUM(Fact_Sales[Volume_MWh])
		formatString: 0
		lineageTag: 486937dd-00d5-49a9-abee-ecb1b00dba4c

	measure 'Average price €/MWh' = DIVIDE([Total revenue €], [Total Volume (MWh)])
		lineageTag: c90c419f-574b-4897-b620-d9661562947e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Margin %' = ```
			
			DIVIDE (
			    [Gross Margin €],
			    [Total Revenue €]
			)
			
			```
		lineageTag: 07a7df61-240b-4f0a-b685-fb775f00e17b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition _Measures-b494ef27-6e2d-4ad3-a787-daa2fa81002a = m
		mode: import
		queryGroup: 'Report Tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

